export const notifications = [
  {
    id: 1,
    title: "Nouvelle commande reçue",
    role: "Responsable stock",
    desc: "Une nouvelle commande de fournitures de peinture a été passée.",
    avatar: "01.png",
    status: "online",
    unread_message: false,
    type: "text",
    date: "2 days ago",
  },
  {
    id: 2,
    title: "Alerte stock bas",
    role: "Chef d'atelier",
    desc: "Le stock de peinture blanche est presque épuisé.",
    avatar: "02.png",
    status: "online",
    unread_message: true,
    type: "text",
    date: "11 am",
  },
  {
    id: 3,
    title: "Réception d'une livraison fournisseur",
    role: "Approvisionneur",
    desc: "La livraison de pinceaux et rouleaux est arrivée.",
    avatar: "03.png",
    status: "busy",
    unread_message: true,
    type: "confirm",
    date: "12 pm",
  },
  {
    id: 4,
    title: "Produit ajouté au catalogue",
    role: "Responsable stock",
    desc: "Nouvelle peinture écologique ajoutée au catalogue produits.",
    avatar: "04.png",
    status: "online",
    unread_message: true,
    type: "text",
    date: "1 pm",
  },
  {
    id: 5,
    title: "Produit en rupture",
    role: "Chef d'atelier",
    desc: "La peinture bleue est actuellement en rupture.",
    avatar: "05.png",
    status: "busy",
    unread_message: false,
    type: "text",
    date: "3 pm",
  },
  {
    id: 6,
    title: "Remise appliquée",
    role: "Responsable stock",
    desc: "Remise saisonnière appliquée à tous les revêtements.",
    avatar: "06.png",
    status: "online",
    unread_message: false,
    type: "text",
    date: "4 pm",
  },
  {
    id: 7,
    title: "Nouveau partenariat fournisseur",
    role: "Approvisionneur",
    desc: "Partenariat établi avec un nouveau fournisseur de pigments.",
    avatar: "07.png",
    status: "online",
    unread_message: true,
    type: "text",
    date: "7 pm",
  },
  {
    id: 8,
    title: "Rappel entretien",
    role: "Chef d'atelier",
    desc: "Rappel : entretien des équipements prévu la semaine prochaine.",
    avatar: "08.png",
    status: "away",
    unread_message: true,
    type: "text",
    date: "10 pm",
  },
  {
    id: 9,
    title: "Audit d'inventaire requis",
    role: "Responsable stock",
    desc: "L'audit d'inventaire trimestriel doit être finalisé.",
    avatar: "09.png",
    status: "offline",
    unread_message: false,
    type: "text",
    date: "10 pm",
  },
  {
    id: 10,
    title: "Profil mis à jour",
    role: "Approvisionneur",
    desc: "Les informations de votre profil utilisateur ont été mises à jour.",
    avatar: "10.png",
    status: "away",
    has_notification: false,
    type: "text",
    date: "10 am",
  },
];

export const messages = [
  {
    title: "Jean Dupont",
    desc: "Hi! How are you doing?.....",
    active: true,
    has_notification: true,
    notification_count: 1,
    image: undefined,
    link: "#",
    date: "11 am",
  },
  {
    title: "Sophie Martin",
    desc: "Hi! How are you doing?.....",
    active: false,
    has_notification: false,
    image: undefined,
    link: "#",
    date: "05 am",
  },
  {
    title: "Pierre Lefebvre",
    desc: "Hi! How are you doing?.....",
    active: false,
    has_notification: true,
    notification_count: 8,
    image: undefined,
    link: "#",
    date: "11 am",
  },
  {
    title: "Luc Bernard",
    desc: "Hi! How are you doing?.....",
    active: true,
    has_notification: false,
    image: undefined,
    link: "#",
    date: "12 am",
  },
  {
    title: "Sophie Martin",
    desc: "Hi! How are you doing?.....",
    active: false,
    has_notification: false,
    image: undefined,
    link: "#",
    date: "10 am",
  },
  {
    title: "Pierre Lefebvre",
    desc: "Hi! How are you doing?.....",
    active: false,
    has_notification: true,
    notification_count: 8,
    image: undefined,
    link: "#",
    date: "10 am",
  },
  {
    title: "Luc Bernard",
    desc: "Hi! How are you doing?.....",
    active: true,
    has_notification: false,
    image: undefined,
    link: "#",
    date: "09 pm",
  },
];

export type Notification = (typeof notifications)[number];
